using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.Events;

public class GameController : MonoBehaviour
{
    [SerializeField] CameraFocus CF;

    
    public void RestartGame()
    {
        DisableInput();
    }
    private void OnEnable()
    {
        PlayerHealth.onGameOver += RestartGame;
    }
    private void OnDisable()
    {
        PlayerHealth.onGameOver -= RestartGame;
    }

    private void DisableInput()
    {
        Debug.Log("Input was disabled");
        gameObject.GetComponent<PlayerInputManager>().gameObject.SetActive(false);
        gameObject.SetActive(false);
    }
}
