using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Portal : MonoBehaviour
{
    [SerializeField] private Portal teleportDestination;
    [SerializeField] private float teleportCoolDownTime;
    private float timer;
    [SerializeField]private bool canTeleport;


    public bool CanTeleport
    {
        get => canTeleport;
        set => canTeleport = value;
    }

    private void Update()
    {
        teleporterCoolDown();
    }


    private void OnTriggerEnter(Collider other)
    {

        if (canTeleport == false) return;
        Debug.Log("hohoho");
        if (other.gameObject.tag == "Player" || other.gameObject.tag.Equals("Grenade") || other.gameObject.tag.Equals("Bullet"))
        {
            Debug.Log("hahaha");
            other.gameObject.transform.position = teleportDestination.transform.position;
            teleportDestination.CanTeleport = false;
        }
    }

    private void teleporterCoolDown()
    {
        if (canTeleport) return;

        timer += Time.deltaTime;
        if(timer >= teleportCoolDownTime)
        {
            canTeleport = true;
            timer = 0f;
        }
    }



   
}
